version = "1.0"

################################################################################
#### ABOUT PANELS
################################################################################

[main]

name.en = "Main configuration"
name.fr = "Configuration principale"

services = ["__APP__"]

    [main.customization]

    name.fr = "Personnalisation de votre instance Grist"
    name.en = "Customize your Grist instance"

    ## (optional) It's also possible with the 'visible' property to only
    ## display the section depending on the user's answers to previous questions.
    ##
    ## Be careful that the 'visible' property should only refer to **previous** questions
    ## Hence, it should not make sense to have a "visible" property on the very first section.
    ##
    ## Also, keep in mind that this feature only works in the webadmin and not in CLI
    ## (therefore a user could be prompted in CLI for a question that may not be relevant)
    # visible = true

        ########################################################################
        #### ABOUT QUESTIONS
        ########################################################################

        ## A section is compound of one or several questions.

        [main.customization.widget_list_url]
        ask.en = "Widgets URL"
        ask.fr = "URL des Widgets"
        type   = "url"

        help.fr = "Spécifiez l'URL pointant vers le manifeste des Widgets. Par défaut https://github.com/gristlabs/grist-widget/releases/download/latest/manifest.json est utilisé"
        help.en = "Specify the url pointing to a widget manifest, by default https://github.com/gristlabs/grist-widget/releases/download/latest/manifest.json is used"
        bind    = "GRIST_WIDGET_LIST_URL:/var/www/__APP__/config.env"

        [main.customization.history_size]
        ask.en = "Documents history size (⚠️ in bytes)"
        ask.fr = "Taille de l'historique des documents (⚠️ en octet)"
        type   = "number"

        help.en = "Maximum size allowed in ActionHistory before pruning. Defaults to 10Mo. ⚠️ A too low value may make the \"Work on a copy\" feature malfunction"
        help.fr = "Nombre maximal de lignes autorisées dans ActionHistory avant l'élagage. La valeur par défaut est de 10Mo. ⚠️ Une valeur trop basse peut entraîner un dysfonctionnement de la fonction « Travailler sur une copie »."
        bind    = "GRIST_ACTION_HISTORY_MAX_BYTES:/var/www/__APP__/config.env"
