#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

redis_db=$(ynh_redis_get_free_db)
admin_email=$(ynh_user_get_info --username=$admin --key=mail)
session_secret=$(ynh_string_random --length=32)
email_header=$(get_email_header)
topest_domain=$(get_topest_domain)
ynh_app_setting_set --key=session_secret --value=$session_secret

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_hide_warnings corepack enable && corepack prepare yarn@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

pushd "$install_dir"
  ynh_script_progression "Installing JS dependencies for the build"
	ynh_hide_warnings ynh_exec_as_app yarn install --frozen-lockfile --network-timeout 600000
  ynh_script_progression "Installing Python dependencies"
	ynh_hide_warnings ynh_exec_as_app yarn install:python
  ynh_script_progression "Building the app (may take a while)"
	ynh_hide_warnings ynh_exec_as_app yarn run build:prod
  ynh_script_progression "Fetching the dependencies for the runtime"
  ynh_hide_warnings ynh_exec_as_app yarn install --prod --frozen-lockfile --network-timeout 600000
	ynh_hide_warnings ynh_exec_as_app yarn cache clean
popd

pushd "$install_dir/sandbox/pyodide"
  ynh_script_progression "Installing the sandbox for formulas"
	ynh_hide_warnings ynh_exec_as_app make setup
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Modern relational spreadsheet" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# CONFIGURE REDIS
#=================================================

ynh_app_setting_set --key=redis_db --value="$redis_db"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="default.env" --destination="$install_dir/default.env"
ynh_config_add --template="custom.env" --destination="$data_dir/custom.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
