#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

redis_db=$(ynh_app_setting_get --key=redis_db)
session_secret=$(ynh_app_setting_get --key=session_secret)
admin_email=$(ynh_user_get_info --username=$admin --key=mail)
email_header=$(get_email_header)
topest_domain=$(get_topest_domain)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

ynh_app_setting_set_default --key=session_secret --value="$(ynh_string_random --length=32)"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="default.env"

#=================================================
# INSTALLING GRIST
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
  ynh_script_progression "Installing JS dependencies for the build"
	ynh_hide_warnings ynh_exec_as_app yarn install --frozen-lockfile --network-timeout 600000
  ynh_script_progression "Installing Python dependencies"
	ynh_hide_warnings ynh_exec_as_app yarn install:python
  ynh_script_progression "Building the app (may take a while)"
	ynh_hide_warnings ynh_exec_as_app yarn run build:prod
  ynh_script_progression "Fetching the dependencies for the runtime"
  ynh_safe_rm ./node_modules/
  ynh_hide_warnings ynh_exec_as_app yarn add --network-timeout 600000 node-gyp node-pre-gyp node-gyp-build node-gyp-build-optional-packages
  ynh_hide_warnings ynh_exec_as_app yarn install --prod --frozen-lockfile --network-timeout 600000
	ynh_hide_warnings ynh_exec_as_app yarn cache clean
popd

pushd "$install_dir/sandbox/pyodide"
  ynh_script_progression "Installing the sandbox for formulas"
	ynh_hide_warnings ynh_exec_as_app make setup
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Modern relational spreadsheet" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="default.env" --destination="$install_dir/default.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
